openapi: 3.0.3
info:
  title: Новостной Портал API
  description: |-
    >## INITIALIZE:
    > Сначала установи PostgreSQL
    > https://www.postgresql.org/download/ \
    > Потом создай базу с любым именем \
    > Создай файл .env и напиши это \
    > DATABASE_URL=postgres://postgres:YourPassword@localhost:5432/YourDatabaseName \
    > Запусти эти команды в консоле:
    >> npm install \
    >> npx prisma migrate dev --name init \
    >> npm start
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Пользователи
    description: Работа с пользователями
paths:
  /createUser:
    post:
      tags:
        - Пользователи
      summary: Создаёт пользователя в БД
      description: Создаёт пользователя в БД. Отдает токен. Сохрани его в localStorage
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegister'
        required: true
      responses:
        '200':
          description: Вернёт JWT Токен
        '204':
          description: Вы ввели не все данные в body
        '409':
          description: Такой пользователь уже есть
  /auth:
    post:
      tags:
        - Пользователи
      summary: Авторизация пользователя
      description: Проверка пользователя в БД. Отдает токен. Сохрани его в localStorage
      operationId: authUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAuthorization'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserAuthorization'
        required: true
      responses:
        '200':
          description: Вернёт JWT Токен
        '204':
          description: Вы ввели не все данные в body
        '401':
          description: Пользователь не найден
  /createSocial:
    post:
      tags:
        - Пользователи
      summary: Добавляет социальную сеть пользователя
      description: Добавляет социальную сеть пользователя
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSocials'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserSocials'
        required: true
      responses:
        '200':
          description: Успех!
        '204':
          description: Вы ввели не все данные в body
  /getUserById/{id}:
    get:
      tags:
        - Пользователи
      summary: Получить информацию о пользователе
      description: Получить информацию о пользователе
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          description: ID пользователя
          schema:
            type: integer
        - name: Authorization
          in: header
          required: true
          description: JWT Токен пользователя
          schema:
            type: integer
      responses:
        '200':
          description: Вернёт пользователя
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '401':
          description: Пользователь не найден
  /getUserInfoById/{id}:
    get:
      tags:
        - Пользователи
      summary: Получить полную информацию о пользователе
      description: Получить полную информацию о пользователе
      operationId: getUserInfo
      parameters:
        - name: id
          in: path
          required: true
          description: ID пользователя
          schema:
            type: integer
      responses:
        '200':
          description: Вернёт информацию о пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        '401':
          description: Пользователь не найден
  /getUserSocialsById/{id}:
    get:
      tags:
        - Пользователи
      summary: Получить все социальные сети пользователя
      description: Получить все социальные сети пользователя
      operationId: getUserSoc
      parameters:
        - name: id
          in: path
          required: true
          description: ID пользователя
          schema:
            type: integer
      responses:
        '200':
          description: Вернёт информацию о всех социальных сетях
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSocials"
        '401':
          description: Пользователь не найден
  /updateUserInfo:
    put:
      tags:
        - Пользователи
      summary: Обновить инфу о пользователе
      description: Обновить инфу о пользователе
      operationId: UserInfoUpdate
      responses:
        '200':
          description: Успех!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoUpdate"
        '204':
          description: Вы ввели не все данные
  /updateSocial:
    put:
      tags:
        - Пользователи
      summary: Обновить социальные сети пользовотеля
      description: Обновить социальные сети пользовотеля
      operationId: UserSocialUpdate
      responses:
        '200':
          description: Успех!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSocialUpdate"
        '204':
          description: Вы ввели не все данные
components:
  schemas:
    User:
      type: object
      properties:
        login:
          type: string
          format: string
          example: test
        password:
          type: string
          format: string
          example: test123
        email:
          type: string
          format: string
          example: test@main.ru
        role:
          type: string
          format: string
          example: user
    UserInfo:
      type: object
      properties:
        user:
          type: integer
          format: int
          example: 1
        about:
          type: string
          format: string
          example: Cool Man =)
        avatar:
          type: string
          format: string
          example: http://localhost:8080/files/Kirill/avatar.png
        nickname:
          type: string
          format: string
          example: Kirill228
        link:
          type: string
          format: string
          example: "@kirushka"
    UserSocials:
      type: array
      items:
        type: object
        properties:
          user:
            type: integer
            format: int
            example: 1
          soc_name:
            type: string
            format: string
            example: Telegram
          avatar:
            type: string
            format: string
            example: https://t.me/@kirill228
    UserRegister:
      type: object
      properties:
        login:
          type: string
          format: string
          example: test
        password:
          type: string
          format: string
          example: test123
        email:
          type: string
          format: string
          example: test@main.ru
    UserAuthorization:
      type: object
      properties:
        login:
          type: string
          format: string
          example: test
        password:
          type: string
          format: string
          example: test123
    UserInfoUpdate:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int
          example: 1
        about:
          type: string
          format: string
          example: Cool Man =)
        avatar:
          type: string
          format: string
          example: http://localhost:8080/files/Kirill/avatar.png
        nickname:
          type: string
          format: string
          example: Kirill228
        link:
          type: string
          format: string
          example: "@kirushka"
    UserSocialUpdate:
      type: array
      items:
        type: object
        required:
          - id
        properties:
          id:
            type: integer
            format: int
            example: 1
          soc_name:
            type: string
            format: string
            example: Telegram
          avatar:
            type: string
            format: string
            example: https://t.me/@kirill228